version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  web:
    build:
      context: .
    ports:
      - '8000:8000'
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis

networks:
  default:
    driver: bridge
